name: Test-Publish
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteorOptions:
          # - '--release=1.2.1'
          # - '--release=1.3.5.1'
          # - '--release=1.5.4.1'
          # - '--release=1.6.1.4'
          # - '--release=1.7.0.5'
          # - '--release=1.8.1'
          # - '--release=1.9.3'
          # - '--release=1.10.2'
          # - '--release=1.11.1'
          # - '--release=2.0-beta.3'
          - '--release=2.5.3'
          - '--release=2.5.6'
          # Latest version
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Meteor cache
        with:
          path: ~/.meteor
          key: ${{ runner.os }}-meteor-${{ matrix.meteorOptions }}
          restore-keys: |
            ${{ runner.os }}-meteor-

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: |
          export PATH=$HOME/.meteor:$PATH
          export METEOR_TEST_OPTION=${{ matrix.meteorOptions }}
          npm test 


  publish:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install npm dependencies
        run: npm ci

      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
